<?php


/**
 * Nano File Management System
 */


// Settings
define('ROOT', "");
define('READ_ONLY', true);


// Values will be auto-generated by the system
$the_mtime = filemtime(__FILE__);
$the_s = DIRECTORY_SEPARATOR;
$the_root = strtr(rtrim(ROOT ?: __DIR__, "\\/"), [
    "\\" => $the_s,
    '/' => $the_s
]);
$the_rules = strtr($_GET['task'] ?? "", [$the_s => '/']);

$the_rules_parts = explode(':', $the_rules, 2);
$the_task = $the_rules_parts[0] ?: 'g';
$the_path = rtrim($the_root . $the_s . ($the_rules_parts[1] ?? ""), $the_s);

$the_view  = '<!DOCTYPE html>';
$the_view .= '<html dir="ltr">';
$the_view .= '<head>';
$the_view .= '<meta content="width=device-width" name="viewport">';
$the_view .= '<meta charset="utf-8">';
$the_view .= '<title>%1$s</title>';
$the_view .= '<link href="?css=' . $the_mtime . '" rel="stylesheet">';
$the_view .= '</head>';
$the_view .= '<body>%2$s';
$the_view .= '<script src="?js=' . $the_mtime . '"></script>';
$the_view .= '</body>';
$the_view .= '</html>';


if (!empty($_GET['css'])) {
    header('Content-Type: text/css');
    // header('Cache-Control: ');
echo <<<CSS

* {
  margin: 0;
  padding: 0;
  font: inherit;
  list-style: none;
  box-sizing: border-box;
}

html {
  font: normal normal 13px/1.4 sans-serif;
  background: #fff;
  color: #000;
}

body {
  padding: 1em;
}

b, h1, h2, h3, h4, h5, h6, strong, th {
  font-weight: bolder;
}

h1 {
  font-size: 200%;
}

h2 {
  font-size: 180%;
}

h3 {
  font-size: 160%;
}

h4 {
  font-size: 140%;
}

h5 {
  font-size: 120%;
}

* + blockquote,
* + h1,
* + h2,
* + h3,
* + h4,
* + h5,
* + h6,
* + ol,
* + p,
* + pre,
* + table,
* + ul {
  margin-top: 1rem;
}

table {
  width: 100%;
  table-layout: fixed;
  border-collapse: collapse;
}

th, td {
  border: 1px solid;
  text-align: left;
  vertical-align: top;
  padding: .25em .5em;
}

main {
  margin: 1em 0;
}

CSS;
} else if (!empty($_GET['js'])) {
    header('Content-Type: application/javascript');
    // header('Cache-Control: ');
echo <<<JS


JS;
} else {
    $the_content  = '<header>';
    $the_content .= '<h1>%1$s</h1>';
    $the_content .= '</header>';
    $the_content .= '<main>';
    $the_content .= '%2$s';
    $the_content .= '</main>';
    $the_content .= '<footer>';
    $the_content .= '</footer>';

    if ('g' === $the_task) {
        $the_table  = '<table>';
        $the_table .= '<thead>';
        $the_table .= '<tr>';
        $the_table .= '<th>Name</th>';
        $the_table .= '<th style="width:12em;" title="Date Create">Date</th>';
        $the_table .= '<th style="width:4em;" title="File Permission">Mode</th>';
        $the_table .= '<th colspan="2" style="width:8em;">Actions</th>';
        $the_table .= '</tr>';
        $the_table .= '</thead>';
        $the_table .= '<tbody>';
        foreach (glob($the_root . $the_s . '*') as $f) {
            $c = filectime($f);
            $the_table .= '<tr>';
            $the_table .= '<td><a href="">' . basename($f) . '</a></td>';
            $the_table .= '<td><time datetime="' . date('c', $c) . '">' . date('Y/m/d H:i:s', $c) . '</time></td>';
            $the_table .= '<td>0600</td>';
            $the_table .= '<td><a href="">Edit</a></td>';
            $the_table .= '<td><a href="">Delete</a></td>';
            $the_table .= '</tr>';
        }
        $the_table .= '</tbody>';
        $the_table .= '</table>';
        $the_content = sprintf($the_content, 'Index of /' . ($the_rules_parts[1] ?? ""), $the_table);
    }

    $the_title = "";
    echo sprintf($the_view, $the_title ? $the_title . ' &middot; Nano' : 'Nano', $the_content);
}
